routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 

Auth::routes();

Route::group(['middleware' => ['admin','auth']], function () {
    Route::prefix('admin')->group(function () {
    // Route::namespace('admin')->group(function () {


        Route::get('dashboard', 'HomeController@index')->name('admin.dashboard');

        Route::resource('galleries','GalleriesController');
        Route::get('galleries-status/{id}/{opr}','GalleriesController@status')->name('admin.galleries.status');

        Route::resource('news','NewsController');
        Route::get('news-status/{id}/{opr}','NewsController@status')->name('admin.news.status');

        Route::resource('welcome','WelcomeController');
        Route::get('welcome-status/{id}/{opr}','WelcomeController@status')->name('admin.welcome.status');

        Route::resource('homeslider','HomeSliderController');
        Route::get('homeslider-status/{id}/{opr}','HomeSliderController@status')->name('admin.homeslider.status');
        Route::post('homeslider-set-position','HomeSliderController@set_sliders_position')->name('admin.homeslider.set.position');

        Route::resource('contactus','ContactusController');
        Route::post('set-contact','OptionsController@set_contact_us')->name('admin.set.contact');

        Route::resource('countries','CountriesController');
        Route::get('countries-status/{id}/{opr}','CountriesController@status')->name('admin.countries.status');

        Route::resource('homesizes','HomesizesController');
        Route::get('homesizes-status/{id}/{opr}','HomesizesController@status')->name('admin.homesizes.status');

        Route::resource('brokers','BrokersController');
        Route::get('brokers-status/{id}/{opr}','BrokersController@status')->name('admin.brokers.status');

        Route::resource('references','ReferencesController');
        Route::get('references-status/{id}/{opr}','ReferencesController@status')->name('admin.references.status');

        Route::resource('aboutus','AboutUsController');
        Route::get('aboutus-status/{id}/{opr}','AboutUsController@status')->name('admin.aboutus.status');

        Route::resource('aboutustabs','AboutUsTabsController');
        Route::get('aboutustabs-status/{id}/{opr}','AboutUsTabsController@status')->name('admin.aboutustabs.status');

    // });
  });
});


Route::get('/',function(){
    return redirect('main');
});

/* get data from below route */

Route::get('get-home-welcome','WelcomeController@get_home_welcome');
Route::get('get-contact-country','CountriesController@get_contact_country');
Route::get('get-contact-homesizes','HomesizesController@get_contact_homesizes');
Route::get('get-contact-brokers','BrokersController@get_contact_brokers');
Route::get('get-contact-references','ReferencesController@get_contact_references');
Route::get('get-option/{type}','OptionsController@get_option');
Route::post('apply-for-enquiry','ContactusController@create');

Route::get('get-home-sliders','HomeSliderController@get_homesliders');
Route::get('get-news','NewsController@get_news');
Route::get('get-single-news/{slug}','NewsController@get_single_news');

Route::get('get-galleries/{type}','GalleriesController@get_galleries');

/* dont touch the above path */

/* Below Is Vue Router Path */
Route::get('vue/{any?}/{id?}', function () {
    return view('front.home');
});


/* Below Is PHP Page Path */
Route::get('main', function () {
    return view('main');
})->name('main');

Route::get('slider', function () {
    return view('slider');
})->name('slider');

Route::get('gallery', function () {
    return view('gallery');
})->name('gallery');

Route::get('contact', function () {
    return view('contact');
})->name('contact');

Route::get('slide', function () {
    return view('slide');
})->name('slide'); 

Route::get('news', function () {
    return view('news');
})->name('news');

Route::get('smart&security', function () {
    return view('smart&security');
})->name('smart&security');

Route::get('amenities', function () {
    return view('amenities');
})->name('amenities');

Route::get('ace', function () {
    return view('ace');
})->name('ace');

Route::get('lifestyle', function () {
    return view('lifestyle');
})->name('lifestyle');

Route::get('location', function () {
    return view('location');
})->name('location');

Route::get('ssgf', function () {
    return view('ssgf');
})->name('ssgf');

Route::get('floor_plan', function () {
    return view('floor_plan');
})->name('floor_plan');

Route::get('views', function () {
    return view('views');
})->name('views');

Route::get('about', function () {
    return view('about');
})->name('about');

Route::get('single_news', function () {
    return view('single_news');
})->name('single_news');


Route::get('/dashboard',function(){
    return redirect('dashboard.index');
});


Route::prefix('dashboard')->group(function () {
    
    Route::get('index', function () {
        return view('dashboard/index');
    })->name('dashboard.index');

    Route::get('gallery', function () {
        return view('dashboard/gallery');
    })->name('dashboard.gallery');

    Route::get('news', function () {
        return view('dashboard/news');
    })->name('dashboard.news');

});

app/Models/Reference.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Reference extends Model
{
    use SoftDeletes;

    protected $table = "references";
    protected $primaryKey = "id";
    protected $dates = ['deleted_at'];
}

app/Http/Controllers/ReferencesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Reference;

class ReferencesController extends Controller
{
    public function index()
    {
        $references = Reference::get();
        return view('admin.references.index',compact('references'));
    }

    public function create()
    {
        return view('admin.references.create');
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'reference_name' => 'required|max:255|regex:/(^[A-Za-z, ]+$)+/',
        ]);

        $reference = new Reference;
        $reference->reference_name=$request->reference_name;

        if($reference->save()){
            
            $notification = array(
                'message' => 'Reference is insert Successfully.', 
                'alert-type' => 'success'
            );

            return redirect()->route('references.index')->with($notification);
        }else{
            return redirect()->back()->route();
        }
    }

    public function show($id)
    {
    }

    public function edit($id)
    {
        $reference = Reference::find($id);
        return view('admin.references.edit',compact('reference'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'reference_name' => 'required|max:255|regex:/(^[A-Za-z, ]+$)+/',
        ]);

        $reference = Reference::find($id);
        $reference->reference_name=$request->reference_name;

        if($reference->save()){
            
            $notification = array(
                'message' => 'Reference is update Successfully.', 
                'alert-type' => 'success'
            );

            return redirect()->route('references.index')->with($notification);
        }else{
            return redirect()->back()->route();
        }
    }

    public function destroy($id)
    {
        $reference = Reference::findOrFail($id);
        $reference->delete();

        $notification = array(
            'message' => 'Reference is delete Successfully.', 
            'alert-type' => 'success'
        );

        return redirect()->route('references.index')->with($notification);
    }

    public function status($id,$opr)
    {
        $reference = Reference::find($id);
        $reference->status = $opr;
        $reference->save();

        $notification = array(
            'message' => 'Reference status update Successfully.', 
            'alert-type' => 'success'
        );

        return redirect()->route('references.index')->with($notification);
    }

    public function get_contact_references()
    {
        $references = Reference::where('status',1)->get();
        return json_encode($references);
    }
}

resources/views/admin/references/create.blade.php
@extends('layouts.admin')

@section('title') Admin | Add Reference @endsection

@section('content')
<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>References</h3>
            </div>
            <div class="col-lg-6">
                <ol class="breadcrumb pull-right">
                    <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
                    <li class="breadcrumb-item">References</li>
                    <li class="breadcrumb-item active">Add Reference</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5>Add Reference</h5>
                </div>
                <form action="{{ route('references.store') }}" class="form theme-form" method="post">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">

                    <div class="card-body">

                        <div class="row">
                            <div class="form-group col-md-4">
                                <label>Reference Name</label>
                                <input type="text" class="form-control" name="reference_name" value="{{ old('reference_name') }}">
                                <span class="text-danger">{{ $errors->first('reference_name') }}</span>
                            </div>
                        </div>

                    </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="{{ route('references.index') }}" class="btn btn-light">Cancel</a>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid starts -->
@endsection

resources/views/admin/references/edit.blade.php
@extends('layouts.admin')

@section('title') Admin | Edit Reference @endsection

@section('content')
<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>References</h3>
            </div>
            <div class="col-lg-6">
                <ol class="breadcrumb pull-right">
                    <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
                    <li class="breadcrumb-item">References</li>
                    <li class="breadcrumb-item active">Edit Reference</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5>Edit Reference</h5>
                </div>
                <form action="{{ route('references.update',$reference->id) }}" class="form theme-form" method="post">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    {{method_field('PUT')}}

                    <div class="card-body">

                        <div class="row">
                            <div class="form-group col-md-4">
                                <label>Reference Name</label>
                                <input type="text" class="form-control" name="reference_name" value="{{ old('reference_name') ? old('reference_name') : $reference->reference_name }}">
                                <span class="text-danger">{{ $errors->first('reference_name') }}</span>
                            </div>
                        </div>

                    </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="{{ route('references.index') }}" class="btn btn-light">Cancel</a>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid starts -->
@endsection

resources/views/admin/references/index.blade.php
@extends('layouts.admin')

@section('title') Admin | References @endsection

@section('content')
<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>References</h3>
            </div>
            <div class="col-lg-6">
                <ol class="breadcrumb pull-right">
                    <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
                    <li class="breadcrumb-item active">References</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5>References</h5>
                    
                    <div class="card-header-right">
                        <a href="{{ route('references.create') }}" class="btn btn-primary" >Add Reference</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="references" class="display">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Reference</th>
                                    <th>Status</th>
                                    <th>Options</th>
                                </tr>
                            </thead>

                            <tbody>
                                @php $i=1 @endphp

                                @foreach($references as $r)
                                <tr>
                                    <td>{{ $i }}</td>
                                    <td>{{ $r->reference_name }}</td>
                                    <td>
                                        @if($r->status == 0)
                                            <a href="{{ route('admin.references.status',[$r->id,'1']) }}" class="txt-danger">Deactive</a>
                                        @elseif($r->status == 1)
                                            <a href="{{ route('admin.references.status',[$r->id,'0']) }}" class="txt-success">Active</a>
                                        @endif
                                    </td>
                                    <td>
                                        <form action="{{ route('references.destroy',$r->id) }}" method="POST">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            {{method_field('DELETE')}}

                                            <a href="{{ route('references.edit',$r->id) }}" class="btn btn-success">
                                                <i class="icofont icofont-pencil-alt-5"></i> Edit
                                            </a>

                                            <button type="submit" class="btn btn-danger">
                                                <i class="icofont icofont-trash"></i>
                                                Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                @php $i++ @endphp
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid starts -->
@endsection

@section('script')

<script type="text/javascript">

    $('#references').DataTable();

</script>
@endsection