routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 

Auth::routes();

Route::group(['middleware' => ['admin','auth']], function () {
    Route::prefix('admin')->group(function () {
    // Route::namespace('admin')->group(function () {


        Route::get('dashboard', 'HomeController@index')->name('admin.dashboard');

        Route::resource('galleries','GalleriesController');
        Route::get('galleries-status/{id}/{opr}','GalleriesController@status')->name('admin.galleries.status');

        Route::resource('news','NewsController');
        Route::get('news-status/{id}/{opr}','NewsController@status')->name('admin.news.status');

        Route::resource('welcome','WelcomeController');
        Route::get('welcome-status/{id}/{opr}','WelcomeController@status')->name('admin.welcome.status');

        Route::resource('homeslider','HomeSliderController');
        Route::get('homeslider-status/{id}/{opr}','HomeSliderController@status')->name('admin.homeslider.status');
        Route::post('homeslider-set-position','HomeSliderController@set_sliders_position')->name('admin.homeslider.set.position');

        Route::resource('contactus','ContactusController');
        Route::post('set-contact','OptionsController@set_contact_us')->name('admin.set.contact');

        Route::resource('countries','CountriesController');
        Route::get('countries-status/{id}/{opr}','CountriesController@status')->name('admin.countries.status');

        Route::resource('homesizes','HomesizesController');
        Route::get('homesizes-status/{id}/{opr}','HomesizesController@status')->name('admin.homesizes.status');

        Route::resource('brokers','BrokersController');
        Route::get('brokers-status/{id}/{opr}','BrokersController@status')->name('admin.brokers.status');

        Route::resource('references','ReferencesController');
        Route::get('references-status/{id}/{opr}','ReferencesController@status')->name('admin.references.status');

        Route::resource('aboutus','AboutUsController');
        Route::get('aboutus-status/{id}/{opr}','AboutUsController@status')->name('admin.aboutus.status');

        Route::resource('aboutustabs','AboutUsTabsController');
        Route::get('aboutustabs-status/{id}/{opr}','AboutUsTabsController@status')->name('admin.aboutustabs.status');

    // });
  });
});


Route::get('/',function(){
    return redirect('main');
});

/* get data from below route */

Route::get('get-home-welcome','WelcomeController@get_home_welcome');
Route::get('get-contact-country','CountriesController@get_contact_country');
Route::get('get-contact-homesizes','HomesizesController@get_contact_homesizes');
Route::get('get-contact-brokers','BrokersController@get_contact_brokers');
Route::get('get-contact-references','ReferencesController@get_contact_references');
Route::get('get-option/{type}','OptionsController@get_option');
Route::post('apply-for-enquiry','ContactusController@create');

Route::get('get-home-sliders','HomeSliderController@get_homesliders');
Route::get('get-news','NewsController@get_news');
Route::get('get-single-news/{slug}','NewsController@get_single_news');

Route::get('get-galleries/{type}','GalleriesController@get_galleries');

/* dont touch the above path */

/* Below Is Vue Router Path */
Route::get('vue/{any?}/{id?}', function () {
    return view('front.home');
});


/* Below Is PHP Page Path */
Route::get('main', function () {
    return view('main');
})->name('main');

Route::get('slider', function () {
    return view('slider');
})->name('slider');

Route::get('gallery', function () {
    return view('gallery');
})->name('gallery');

Route::get('contact', function () {
    return view('contact');
})->name('contact');

Route::get('slide', function () {
    return view('slide');
})->name('slide'); 

Route::get('news', function () {
    return view('news');
})->name('news');

Route::get('smart&security', function () {
    return view('smart&security');
})->name('smart&security');

Route::get('amenities', function () {
    return view('amenities');
})->name('amenities');

Route::get('ace', function () {
    return view('ace');
})->name('ace');

Route::get('lifestyle', function () {
    return view('lifestyle');
})->name('lifestyle');

Route::get('location', function () {
    return view('location');
})->name('location');

Route::get('ssgf', function () {
    return view('ssgf');
})->name('ssgf');

Route::get('floor_plan', function () {
    return view('floor_plan');
})->name('floor_plan');

Route::get('views', function () {
    return view('views');
})->name('views');

Route::get('about', function () {
    return view('about');
})->name('about');

Route::get('single_news', function () {
    return view('single_news');
})->name('single_news');


Route::get('/dashboard',function(){
    return redirect('dashboard.index');
});


Route::prefix('dashboard')->group(function () {
    
    Route::get('index', function () {
        return view('dashboard/index');
    })->name('dashboard.index');

    Route::get('gallery', function () {
        return view('dashboard/gallery');
    })->name('dashboard.gallery');

    Route::get('news', function () {
        return view('dashboard/news');
    })->name('dashboard.news');

});

app/Models/Welcome.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Welcome extends Model
{
	use SoftDeletes;

    protected $table = "welcome";
    protected $primaryKey = "id";
    protected $dates = ['deleted_at'];
}

app/Http/Controllers/WelcomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Welcome;
use File;

class WelcomeController extends Controller
{
    public function index()
    {
        $welcome = Welcome::get();
        return view('admin.welcome.index',compact('welcome'));
    }

    public function create()
    {
        return view('admin.welcome.create');
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'headline' => 'required|max:255',
            'button_title' =>'required',
            'link' => 'required',
            'background_url' => 'required|url',
            'introcontent' => 'required',
        ]);

        $welcome = new Welcome();
        $welcome->headline = $request->headline;
        $welcome->button_title = $request->button_title;
        $welcome->link = $request->link;
        $welcome->introcontent = $request->introcontent;
        $welcome->background_url = $request->background_url;


        /*$background_url = $request->file('background_url');
        $welcome->background_url = date('YmdHis').".".$background_url->getClientOriginalExtension();
        $destination = public_path('uploads/welcome/');
        $background_url->move($destination,$welcome->background_url);*/

        if($welcome->save()){
            
            $notification = array(
                'message' => 'Welcome is Insert Successfully.', 
                'alert-type' => 'success'
            );

            return redirect()->route('welcome.index')->with($notification);
        }else{
            return redirect()->back()->route();
        }
    }

    public function show($id)
    {
    }

    public function edit($id)
    {
        $welcome = Welcome::find($id);
        return view('admin.welcome.edit',compact('welcome'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'headline' => 'required|max:255',
            'button_title' =>'required',
            'link' => 'required',
            'background_url' => 'url',
            'introcontent' => 'required',
        ]);

        $welcome = Welcome::find($id);
        $welcome->headline = $request->headline;
        $welcome->button_title = $request->button_title;
        $welcome->link = $request->link;
        $welcome->introcontent = $request->introcontent;
        $welcome->background_url = $request->background_url;

        /*if($request->hasFile('background_url'))
        {
            $image_path = "uploads/welcome/".$welcome->background_url;
        
            if(File::exists($image_path)) {
                File::delete($image_path);
            }

            $background_url = $request->file('background_url');
            //$welcome->background_url = date('YmdHis').".".$background_url->getClientOriginalExtension();
            $welcome->background_url = 'videos.'.$background_url->getClientOriginalExtension();
            $destination = public_path('uploads/welcome/');
            $background_url->move($destination,$welcome->background_url);
        }*/

        if($welcome->save()){
            
            $notification = array(
                'message' => 'Welcome is Update Successfully.', 
                'alert-type' => 'success'
            );

            return redirect()->route('welcome.index')->with($notification);
        }else{
            return redirect()->back()->route();
        }
    }

    public function destroy($id)
    {
        $welcome = Welcome::findOrFail($id);

        /*$background_url = "uploads/welcome/".$welcome->background_url;
    
        if(File::exists($background_url)) {
            File::delete($background_url);
        }*/

        $welcome->delete();

        $notification = array(
            'message' => 'Welcome is delete Successfully.', 
            'alert-type' => 'success'
        );

        return redirect()->route('welcome.index')->with($notification);
    }

    public function status($id,$opr)
    {
        if($opr == 1)
        {
            $wel = Welcome::where('status',1)->count();

            if($wel >= 1)
            {
                $notification = array(
                    'message' => 'Sorry You Can Active only one Welcome record at a Time.', 
                    'alert-type' => 'warning'
                );

                return redirect()->route('welcome.index')->with($notification);
            }
            else
            {
                $welcome = Welcome::find($id);
                $welcome->status = $opr;
                $welcome->save();

                $notification = array(
                    'message' => 'Welcome status update Successfully.', 
                    'alert-type' => 'success'
                );
                
                return redirect()->route('welcome.index')->with($notification);
            }
        }
        else
        {
            $welcome = Welcome::find($id);
            $welcome->status = $opr;
            $welcome->save();

            $notification = array(
                'message' => 'Welcome status update Successfully.', 
                'alert-type' => 'success'
            );
            
            return redirect()->route('welcome.index')->with($notification);
        }
    }


    public function get_home_welcome()
    {
        $welcome = Welcome::where('status',1)->first();
        return json_encode($welcome);
    }
}

resources/views/admin/welcome/create.blade.php
@extends('layouts.admin')

@section('title') Admin | Welcome @endsection

@section('content')
<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>Welcome</h3>
            </div>
            <div class="col-lg-6">
                <ol class="breadcrumb pull-right">
                    <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
                    <li class="breadcrumb-item">Welcome</li>
                    <li class="breadcrumb-item active">Add Welcome</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5>Add Welcome</h5>
                </div>
                <form action="{{ route('welcome.store') }}" class="form theme-form" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <div class="card-body">

                        <div class="row">
                            <div class="form-group col-md-4">
                                <label>Welcome Headline</label>
                                <input type="text" class="form-control" name="headline" value="{{ old('headline') }}">
                                <span class="text-danger">{{ $errors->first('headline') }}</span>
                            </div>
                            <div class="form-group col-md-4">
                                <label>Welcome Video Link</label>
                                <input type="text" class="form-control" name="background_url" value="{{ old('background_url') }}">
                                <span class="text-danger">{{ $errors->first('background_url') }}</span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-4">
                                <label>Welcome Button Title</label>
                                <input type="text" class="form-control" name="button_title" value="{{ old('button_title') }}">
                                <span class="text-danger">{{ $errors->first('button_title') }}</span>
                            </div>
                            <div class="form-group col-md-4">
                                <label>Welcome Link</label>
                                <input type="text" class="form-control" name="link" value="{{ old('link') }}">
                                <span class="text-danger">{{ $errors->first('link') }}</span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-8">
                                <label>Introcontent</label>
                                <textarea class="form-control" id="introcontent" name="introcontent">{{ old('introcontent') }}</textarea>
                                <span class="text-danger">{{ $errors->first('introcontent') }}</span>
                            </div>
                        </div>

                    </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="{{ route('welcome.index') }}" class="btn btn-light">Cancel</a>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid starts -->
@endsection

@section('script')

<!--ckeditor js-->
<script src="{{ asset('back/js/ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('back/js/ckeditor/styles.js') }}"></script>
<script src="{{ asset('back/js/ckeditor/adapters/jquery.js') }}"></script>
<script type="text/javascript">
    CKEDITOR.replace( 'introcontent', {
        on: {
            contentDom: function( evt ) {
                // Allow custom context menu only with table elemnts.
                evt.editor.editable().on( 'contextmenu', function( contextEvent ) {
                    var path = evt.editor.elementPath();

                    if ( !path.contains( 'table' ) ) {
                        contextEvent.cancel();
                    }
                }, null, null, 5 );
            }
        }
    } );
</script>
@endsection

resources/views/admin/welcome/edit.blade.php
@extends('layouts.admin')

@section('title') Admin | Welcome @endsection

@section('content')
<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>Welcome</h3>
            </div>
            <div class="col-lg-6">
                <ol class="breadcrumb pull-right">
                    <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
                    <li class="breadcrumb-item">Welcome</li>
                    <li class="breadcrumb-item active">Edit Welcome</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5>Edit Welcome</h5>
                </div>
                <form action="{{ route('welcome.update',$welcome->id) }}" class="form theme-form" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    {{method_field('PUT')}}

                    <div class="card-body">

                        <div class="row">
                            <div class="form-group col-md-4">
                                <label>Welcome Headline</label>
                                <input type="text" class="form-control" name="headline" value="{{ old('headline') ? old('headline') : $welcome->headline }}">
                                <span class="text-danger">{{ $errors->first('headline') }}</span>
                            </div>
                            <div class="form-group col-md-4">
                                <label>Welcome Video Link</label>
                                <input type="text" class="form-control" name="background_url" value="{{ old('background_url') ? old('background_url') : $welcome->background_url }}">
                                <span class="text-danger">{{ $errors->first('background_url') }}</span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-4">
                                <label>Welcome Button Title</label>
                                <input type="text" class="form-control" name="button_title" value="{{ old('button_title') ? old('button_title') : $welcome->button_title }}">
                                <span class="text-danger">{{ $errors->first('button_title') }}</span>
                            </div>
                            <div class="form-group col-md-4">
                                <label>Welcome Link</label>
                                <input type="text" class="form-control" name="link" value="{{ old('link') ? old('link') : $welcome->link }}">
                                <span class="text-danger">{{ $errors->first('link') }}</span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-8">
                                <label>Introcontent</label>
                                <textarea class="form-control" id="introcontent" name="introcontent">{{ old('introcontent') ? old('introcontent') : $welcome->introcontent }}</textarea>
                                <span class="text-danger">{{ $errors->first('introcontent') }}</span>
                            </div>
                        </div>

                    </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="{{ route('welcome.index') }}" class="btn btn-light">Cancel</a>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid starts -->
@endsection

@section('script')

<!--ckeditor js-->
<script src="{{ asset('back/js/ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('back/js/ckeditor/styles.js') }}"></script>
<script src="{{ asset('back/js/ckeditor/adapters/jquery.js') }}"></script>
<script type="text/javascript">
    CKEDITOR.replace( 'introcontent', {
        on: {
            contentDom: function( evt ) {
                // Allow custom context menu only with table elemnts.
                evt.editor.editable().on( 'contextmenu', function( contextEvent ) {
                    var path = evt.editor.elementPath();

                    if ( !path.contains( 'table' ) ) {
                        contextEvent.cancel();
                    }
                }, null, null, 5 );
            }
        }
    } );
</script>
@endsection

resources/views/admin/welcome/index.blade.php
@extends('layouts.admin')

@section('title') Admin | Welcome @endsection

@section('style')
<style>
    .morecontent span {
        display: none;
    }
    .morelink {
        display: block;
    }
</style>
@endsection

@section('content')
<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>welcome</h3>
            </div>
            <div class="col-lg-6">
                <ol class="breadcrumb pull-right">
                    <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
                    <li class="breadcrumb-item active">welcome</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5>welcome</h5>
                    
                    <div class="card-header-right">
                        <a href="{{ route('welcome.create') }}" class="btn btn-primary" >Add welcome</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="welcome" class="display">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Headline</th>
                                    <th>Introcontent</th>
                                    <th>Status</th>
                                    <th>Options</th>
                                </tr>
                            </thead>

                            <tbody>
                                @php $i=1 @endphp

                                @foreach($welcome as $w)
                                <tr>
                                    <td>{{ $i }}</td>
                                    <td>{{ $w->headline }}</td>
                                    <td class="more" width="40%">{!! $w->introcontent !!}</td>
                                    <td>
                                        @if($w->status == 0)
                                            <a href="{{ route('admin.welcome.status',[$w->id,'1']) }}" class="txt-danger">Deactive</a>
                                        @elseif($w->status == 1)
                                            <a href="{{ route('admin.welcome.status',[$w->id,'0']) }}" class="txt-success">Active</a>
                                        @endif
                                    </td>
                                    <td>
                                        <form action="{{ route('welcome.destroy',$w->id) }}" method="POST">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            {{method_field('DELETE')}}

                                            <a href="{{ route('welcome.edit',$w->id) }}" class="btn btn-success">
                                                <i class="icofont icofont-pencil-alt-5"></i> Edit
                                            </a>

                                            <!-- <button type="submit" class="btn btn-danger">
                                                <i class="icofont icofont-trash"></i>
                                                Delete
                                            </button> -->
                                        </form>
                                    </td>
                                </tr>
                                @php $i++ @endphp
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid starts -->
@endsection

@section('script')

<script type="text/javascript">

    $('#welcome').DataTable();


    $(document).ready(function() {
        var showChar = 100;
        var ellipsestext = "...";
        var moretext = "more";
        var lesstext = "less";
        $('.more').each(function() {
            var content = $(this).html();
            $('.morecontent > span').hide();

            if(content.length > showChar) {

                var c = content.substr(0, showChar);
                var h = content.substr(showChar-1, content.length - showChar);

                var html = c + '<span class="moreelipses">'+ellipsestext+'</span>&nbsp;<span class="morecontent"><span>' + h + '</span>&nbsp;&nbsp;<a href="" class="morelink">'+moretext+'</a></span>';

                $(this).html(html);
            }

        });

        $(".morelink").click(function(){
            if($(this).hasClass("less")) {
                $(this).removeClass("less");
                $(this).html(moretext);
            } else {
                $(this).addClass("less");
                $(this).html(lesstext);
            }
            $(this).parent().prev().toggle();
            $(this).prev().toggle();
            return false;
        });
    });

</script>
@endsection