routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 

Auth::routes();

Route::group(['middleware' => ['admin','auth']], function () {
    Route::prefix('admin')->group(function () {
    // Route::namespace('admin')->group(function () {


        Route::get('dashboard', 'HomeController@index')->name('admin.dashboard');

        Route::resource('galleries','GalleriesController');
        Route::get('galleries-status/{id}/{opr}','GalleriesController@status')->name('admin.galleries.status');

        Route::resource('news','NewsController');
        Route::get('news-status/{id}/{opr}','NewsController@status')->name('admin.news.status');

        Route::resource('welcome','WelcomeController');
        Route::get('welcome-status/{id}/{opr}','WelcomeController@status')->name('admin.welcome.status');

        Route::resource('homeslider','HomeSliderController');
        Route::get('homeslider-status/{id}/{opr}','HomeSliderController@status')->name('admin.homeslider.status');
        Route::post('homeslider-set-position','HomeSliderController@set_sliders_position')->name('admin.homeslider.set.position');

        Route::resource('contactus','ContactusController');
        Route::post('set-contact','OptionsController@set_contact_us')->name('admin.set.contact');

        Route::resource('countries','CountriesController');
        Route::get('countries-status/{id}/{opr}','CountriesController@status')->name('admin.countries.status');

        Route::resource('homesizes','HomesizesController');
        Route::get('homesizes-status/{id}/{opr}','HomesizesController@status')->name('admin.homesizes.status');

        Route::resource('brokers','BrokersController');
        Route::get('brokers-status/{id}/{opr}','BrokersController@status')->name('admin.brokers.status');

        Route::resource('references','ReferencesController');
        Route::get('references-status/{id}/{opr}','ReferencesController@status')->name('admin.references.status');

        Route::resource('aboutus','AboutUsController');
        Route::get('aboutus-status/{id}/{opr}','AboutUsController@status')->name('admin.aboutus.status');

        Route::resource('aboutustabs','AboutUsTabsController');
        Route::get('aboutustabs-status/{id}/{opr}','AboutUsTabsController@status')->name('admin.aboutustabs.status');

    // });
  });
});


Route::get('/',function(){
    return redirect('main');
});

/* get data from below route */

Route::get('get-home-welcome','WelcomeController@get_home_welcome');
Route::get('get-contact-country','CountriesController@get_contact_country');
Route::get('get-contact-homesizes','HomesizesController@get_contact_homesizes');
Route::get('get-contact-brokers','BrokersController@get_contact_brokers');
Route::get('get-contact-references','ReferencesController@get_contact_references');
Route::get('get-option/{type}','OptionsController@get_option');
Route::post('apply-for-enquiry','ContactusController@create');

Route::get('get-home-sliders','HomeSliderController@get_homesliders');
Route::get('get-news','NewsController@get_news');
Route::get('get-single-news/{slug}','NewsController@get_single_news');

Route::get('get-galleries/{type}','GalleriesController@get_galleries');

/* dont touch the above path */

/* Below Is Vue Router Path */
Route::get('vue/{any?}/{id?}', function () {
    return view('front.home');
});


/* Below Is PHP Page Path */
Route::get('main', function () {
    return view('main');
})->name('main');

Route::get('slider', function () {
    return view('slider');
})->name('slider');

Route::get('gallery', function () {
    return view('gallery');
})->name('gallery');

Route::get('contact', function () {
    return view('contact');
})->name('contact');

Route::get('slide', function () {
    return view('slide');
})->name('slide'); 

Route::get('news', function () {
    return view('news');
})->name('news');

Route::get('smart&security', function () {
    return view('smart&security');
})->name('smart&security');

Route::get('amenities', function () {
    return view('amenities');
})->name('amenities');

Route::get('ace', function () {
    return view('ace');
})->name('ace');

Route::get('lifestyle', function () {
    return view('lifestyle');
})->name('lifestyle');

Route::get('location', function () {
    return view('location');
})->name('location');

Route::get('ssgf', function () {
    return view('ssgf');
})->name('ssgf');

Route::get('floor_plan', function () {
    return view('floor_plan');
})->name('floor_plan');

Route::get('views', function () {
    return view('views');
})->name('views');

Route::get('about', function () {
    return view('about');
})->name('about');

Route::get('single_news', function () {
    return view('single_news');
})->name('single_news');


Route::get('/dashboard',function(){
    return redirect('dashboard.index');
});


Route::prefix('dashboard')->group(function () {
    
    Route::get('index', function () {
        return view('dashboard/index');
    })->name('dashboard.index');

    Route::get('gallery', function () {
        return view('dashboard/gallery');
    })->name('dashboard.gallery');

    Route::get('news', function () {
        return view('dashboard/news');
    })->name('dashboard.news');

});

app/Models/HomeSlider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class HomeSlider extends Model
{
	use SoftDeletes;

    protected $table = "homesliders";
    protected $primaryKey = "id";
    protected $dates = ['deleted_at'];
}

app/Http/Controllers/HomeSliderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\HomeSlider;
use File;

class HomeSliderController extends Controller
{
    public function index()
    {
        $sliders = HomeSlider::orderBy('orderno')->get();
        return view('admin.homeslider.index',compact('sliders'));
    }
    public function create()
    {
        return view('admin.homeslider.create');
    }
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' => 'required|max:255',
            'subtitle' => 'required|max:255',
            'link' => 'required|url',
            'background_image' => 'required|mimes:jpeg,jpg,png',
            'font_color' => 'required',
            'background_color' => 'required',
            'description' => 'required',
        ]);

        $slider = new HomeSlider();
        $slider->title = $request->title;
        $slider->subtitle = $request->subtitle;
        $slider->description = $request->description;
        $slider->link = $request->link;
        $slider->font_color = $request->font_color;
        $slider->background_color = $request->background_color;

        $slider_image = $request->file('background_image');
        $slider->background_image = date('YmdHis').".".$slider_image->getClientOriginalExtension();
        $destination = public_path('uploads/homeslider/');
        $slider_image->move($destination,$slider->background_image);

        if($slider->save()){
            
            $notification = array(
                'message' => 'Slider is Insert Successfully.', 
                'alert-type' => 'success'
            );

            return redirect()->route('homeslider.index')->with($notification);
        }else{
            return redirect()->back()->route();
        }
    }
    
    public function show($id)
    {
    }

    public function edit($id)
    {
        $slider = HomeSlider::find($id);

        return view('admin.homeslider.edit',compact('slider'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'title' => 'required|max:255',
            'subtitle' => 'required|max:255',
            'link' => 'required|url',
            'background_image' => 'mimes:jpeg,jpg,png',
            'font_color' => 'required',
            'background_color' => 'required',
            'description' => 'required',
        ]);

        $slider = HomeSlider::find($id);
        $slider->title = $request->title;
        $slider->subtitle = $request->subtitle;
        $slider->description = $request->description;
        $slider->link = $request->link;
        $slider->font_color = $request->font_color;
        $slider->background_color = $request->background_color;

        if($request->hasFile('background_image'))
        {
            $image_path = "uploads/homeslider/".$slider->image;
        
            if(File::exists($image_path)) {
                File::delete($image_path);
            }

            $slider_image = $request->file('background_image');
            $slider->background_image = date('YmdHis').".".$slider_image->getClientOriginalExtension();
            $destination = public_path('uploads/homeslider/');
            $slider_image->move($destination,$slider->background_image);
        }

        if($slider->save()){
            
            $notification = array(
                'message' => 'Slider is Update Successfully.', 
                'alert-type' => 'success'
            );

            return redirect()->route('homeslider.index')->with($notification);
        }else{
            return redirect()->back()->route();
        }
    }

    public function destroy($id)
    {
        $slider = HomeSlider::findOrFail($id);

        /*$background_image = "uploads/homeslider/".$slider->background_image;
    
        if(File::exists($background_image)) {
            File::delete($background_image);
        }*/

        $slider->delete();

        $notification = array(
            'message' => 'Slider is delete Successfully.', 
            'alert-type' => 'success'
        );

        return redirect()->route('homeslider.index')->with($notification);
    }

    public function status($id,$opr)
    {
        $slider = HomeSlider::find($id);
        $slider->status = $opr;
        $slider->save();

        $notification = array(
            'message' => 'Home Slider status update Successfully.', 
            'alert-type' => 'success'
        );

        return redirect()->route('homeslider.index')->with($notification);
    }

    public function set_sliders_position(Request $request)
    {
        foreach ($request->newPosition as $key => $value)
        {
            $slider = HomeSlider::where('id',$key)->update(['orderno'=>$value]);
        }

        /*$response['status'] = 'success';
        echo json_encode($response);*/
    }

    public function get_homesliders()
    {
        $sliders = HomeSlider::orderBy('orderno')->get();
        return json_encode($sliders);
    }
}

resources/views/admin/homeslider/create.blade.php
@extends('layouts.admin')

@section('title') Admin | Home Slider @endsection

@section('style')
    <style>
        input[type="color"] {
            padding: 0;
            border: none;
            height: 50px;
            width: 50px;
            vertical-align: middle;
        }
    </style>
@endsection

@section('content')
<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>Home Slider</h3>
            </div>
            <div class="col-lg-6">
                <ol class="breadcrumb pull-right">
                    <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
                    <li class="breadcrumb-item">Home Slider</li>
                    <li class="breadcrumb-item active">Add Slider</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5>Add Slider</h5>
                </div>
                <form action="{{ route('homeslider.store') }}" class="form theme-form" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">

                    <div class="card-body">

                        <div class="row">
                            <div class="form-group col-md-4">
                                <label>Slider Title</label>
                                <input type="text" class="form-control" name="title" value="{{ old('title') }}">
                                <span class="text-danger">{{ $errors->first('title') }}</span>
                            </div>
                            <div class="form-group col-md-4">
                                <label>Slider Sub Title</label>
                                <input type="text" class="form-control" name="subtitle" value="{{ old('subtitle') }}">
                                <span class="text-danger">{{ $errors->first('subtitle') }}</span>
                            </div>
                        </div>


                        <div class="row">
                            <div class="form-group col-md-4">
                                <label>Slider Link</label>
                                <input type="text" class="form-control" name="link" value="{{ old('link') }}">
                                <span class="text-danger">{{ $errors->first('link') }}</span>
                            </div>
                            <div class="form-group col-md-4">
                                <label>Slider Image</label>
                                <input type="file" class="form-control" name="background_image" id="background_image">
                                <span class="text-danger">Note: Please select image width=1110 and height=443</span>
                                <span class="text-danger">{{ $errors->first('background_image') }}</span>
                            </div>
                            <div class="form-group col-md-4">
                                <img src="" id="slider_image_prev" style="width: 50%;">
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-4">
                                <label>Select Font Color picker</label>
                                <input class="form-control" type="color" name="font_color" value="#ffffff">
                                <span class="text-danger">{{ $errors->first('font_color') }}</span>
                            </div>
                            <div class="form-group col-md-4">
                                <label>Select Background Color picker</label>
                                <input class="form-control" type="color" name="background_color" value="#ffffff">
                                <span class="text-danger">{{ $errors->first('background_color') }}</span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-8">
                                <label>Slider Description</label>
                                <textarea class="form-control" id="description" name="description">{{ old('description') }}</textarea>
                                <span class="text-danger">{{ $errors->first('description') }}</span>
                            </div>
                        </div>

                    </div>

                    <div class="card-footer">
                        <div class="row">
                            <div class="form-group col-md-2">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                            <div class="form-group col-md-2">
                                <a href="{{ route('homeslider.index') }}" class="btn btn-light">Cancel</a>
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid starts -->
@endsection

@section('script')

<!--ckeditor js-->
<script src="{{ asset('back/js/ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('back/js/ckeditor/styles.js') }}"></script>
<script src="{{ asset('back/js/ckeditor/adapters/jquery.js') }}"></script>
<script type="text/javascript">
    CKEDITOR.replace( 'description', {
        on: {
            contentDom: function( evt ) {
                // Allow custom context menu only with table elemnts.
                evt.editor.editable().on( 'contextmenu', function( contextEvent ) {
                    var path = evt.editor.elementPath();

                    if ( !path.contains( 'table' ) ) {
                        contextEvent.cancel();
                    }
                }, null, null, 5 );
            }
        }
    } );
</script>

<script type="text/javascript">
    function background_image(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function(e) {
          $('#slider_image_prev').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
      }
    }

    $("#background_image").change(function() {
      background_image(this);
    });
</script>
@endsection

resources/views/admin/homeslider/edit.blade.php
@extends('layouts.admin')

@section('title') Admin | Home Slider @endsection

@section('style')
    <style>
        input[type="color"] {
            padding: 0;
            border: none;
            height: 50px;
            width: 50px;
            vertical-align: middle;
        }
    </style>
@endsection

@section('content')
<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>Home Slider</h3>
            </div>
            <div class="col-lg-6">
                <ol class="breadcrumb pull-right">
                    <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
                    <li class="breadcrumb-item">Home Slider</li>
                    <li class="breadcrumb-item active">Edit Slider</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5>Edit Slider</h5>
                </div>
                <form action="{{ route('homeslider.update',$slider->id) }}" class="form theme-form" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    {{method_field('PUT')}}

                    <div class="card-body">

                        <div class="row">
                            <div class="form-group col-md-4">
                                <label>Slider Title</label>
                                <input type="text" class="form-control" name="title" value="{{ old('title') ? old('title') : $slider->title }}">
                                <span class="text-danger">{{ $errors->first('title') }}</span>
                            </div>
                            <div class="form-group col-md-4">
                                <label>Slider Sub Title</label>
                                <input type="text" class="form-control" name="subtitle" value="{{ old('subtitle') ? old('subtitle') : $slider->subtitle }}">
                                <span class="text-danger">{{ $errors->first('subtitle') }}</span>
                            </div>
                        </div>


                        <div class="row">
                            <div class="form-group col-md-4">
                                <label>Slider Link</label>
                                <input type="text" class="form-control" name="link" value="{{ old('link') ? old('link') : $slider->link }}">
                                <span class="text-danger">{{ $errors->first('link') }}</span>
                            </div>
                            <div class="form-group col-md-4">
                                <label>Slider Image</label>
                                <input type="file" class="form-control" name="background_image" id="background_image">
                                <span class="text-danger">Note: Please select image width=1110 and height=443</span>
                                <span class="text-danger">{{ $errors->first('background_image') }}</span>
                            </div>
                            <div class="form-group col-md-4">
                                <img src="{{ url('uploads/homeslider') }}/{{ $slider->background_image }}" id="slider_image_prev" style="width: 50%;">
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-4">
                                <label>Select Font Color picker</label>
                                <input class="form-control" type="color" name="font_color" value="{{ old('font_color') ? old('font_color') : $slider->font_color }}">
                                <span class="text-danger">{{ $errors->first('font_color') }}</span>
                            </div>
                            <div class="form-group col-md-4">
                                <label>Select Background Color picker</label>
                                <input class="form-control" type="color" name="background_color" value="{{ old('background_color') ? old('background_color') : $slider->background_color }}">
                                <span class="text-danger">{{ $errors->first('background_color') }}</span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-8">
                                <label>Slider Description</label>
                                <textarea class="form-control" id="description" name="description">{{ old('description') ? old('description') : $slider->description }}</textarea>
                                <span class="text-danger">{{ $errors->first('description') }}</span>
                            </div>
                        </div>

                    </div>

                    <div class="card-footer">
                        <div class="row">
                            <div class="form-group col-md-2">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                            <div class="form-group col-md-2">
                                <a href="{{ route('homeslider.index') }}" class="btn btn-light">Cancel</a>
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid starts -->
@endsection

@section('script')

<!--ckeditor js-->
<script src="{{ asset('back/js/ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('back/js/ckeditor/styles.js') }}"></script>
<script src="{{ asset('back/js/ckeditor/adapters/jquery.js') }}"></script>
<script type="text/javascript">
    CKEDITOR.replace( 'description', {
        on: {
            contentDom: function( evt ) {
                // Allow custom context menu only with table elemnts.
                evt.editor.editable().on( 'contextmenu', function( contextEvent ) {
                    var path = evt.editor.elementPath();

                    if ( !path.contains( 'table' ) ) {
                        contextEvent.cancel();
                    }
                }, null, null, 5 );
            }
        }
    });
</script>

<script type="text/javascript">
    function background_image(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function(e) {
          $('#slider_image_prev').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
      }
    }

    $("#background_image").change(function() {
      background_image(this);
    });
</script>
@endsection

resources/views/admin/homeslider/index.blade.php
@extends('layouts.admin')

@section('title') Admin | Home Slider @endsection

@section('style')
<link rel="stylesheet" type="text/css" href="{{ asset('back/css/datatable-extension.css') }}" />
<style>
    .morecontent span {
        display: none;
    }
    .morelink {
        display: block;
    }
</style>
@endsection

@section('content')
<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-6">
                <h3>Home Slider</h3>
            </div>
            <div class="col-lg-6">
                <ol class="breadcrumb pull-right">
                    <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
                    <li class="breadcrumb-item active">Home Slider</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends -->

<!-- Container-fluid starts -->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5>Home Slider</h5>
                    
                    <div class="card-header-right">
                        <!-- <a href="{{ route('homeslider.create') }}" class="btn btn-primary" >Add Sliders</a> -->
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="sliders" class="display">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Image</th>
                                    <th>Title</th>
                                    <th>Sub Title</th>
                                    <th>Description</th>
                                    <th>Status</th>
                                    <th>Options</th>
                                </tr>
                            </thead>

                            <tbody>
                                @php $i=1 @endphp

                                @foreach($sliders as $s)
                                <tr id="{{$s->id}}">
                                    <td>{{ $i }}</td>
                                    <td><img src="{{ url('uploads/homeslider') }}/{{ $s->background_image }}" style="width: 100px;"></td>
                                    <td>{{ $s->title }}</td>
                                    <td>{{ $s->subtitle }}</td>
                                    <td width="30%" class="more">{!! $s->description !!}</td>
                                    <td>
                                        @if($s->status == 0)
                                            <a href="{{ route('admin.homeslider.status',[$s->id,'1']) }}" class="txt-danger">Deactive</a>
                                        @elseif($s->status == 1)
                                            <a href="{{ route('admin.homeslider.status',[$s->id,'0']) }}" class="txt-success">Active</a>
                                        @endif
                                    </td>
                                    <td>
                                        <form action="{{ route('homeslider.destroy',$s->id) }}" method="POST">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            {{method_field('DELETE')}}

                                            <a href="{{ route('homeslider.edit',$s->id) }}" class="btn btn-success">
                                                <i class="icofont icofont-pencil-alt-5"></i> Edit
                                            </a>

                                            <button type="submit" class="btn btn-danger">
                                                <i class="icofont icofont-trash"></i>
                                                Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                @php $i++ @endphp
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid starts -->
@endsection

@section('script')

<!--datatable extension js-->
<script src="{{ asset('back/js/dataTables.rowReorder.min.js') }}"></script>

<script type="text/javascript">

    var table = $('#sliders').DataTable( {
        rowReorder: true
    });

    table.on( 'row-reorder', function ( e, diff, edit ) {

        var newPosition = new Array();

        newPosition = edit.values;

        $.ajax({
            url: '{{ route("admin.homeslider.set.position") }}',
            type: 'POST',
            data: { "_token": "{{ csrf_token() }}","newPosition":newPosition },
            success: function (s) {
                console.log(s)
            }
        });

    });

</script>

<script type="text/javascript">
    $(document).ready(function() {
        var showChar = 100;
        var ellipsestext = "...";
        var moretext = "more";
        var lesstext = "less";
        $('.more p').each(function() {
            var content = $(this).html();
            $('.morecontent > span').hide();

            if(content.length > showChar) {

                var c = content.substr(0, showChar);
                var h = content.substr(showChar-1, content.length - showChar);

                var html = c + '<span class="moreelipses">'+ellipsestext+'</span>&nbsp;<span class="morecontent"><span>' + h + '</span>&nbsp;&nbsp;<a href="" class="morelink">'+moretext+'</a></span>';

                $(this).html(html);
            }

        });

        $(".morelink").click(function(){
            if($(this).hasClass("less")) {
                $(this).removeClass("less");
                $(this).html(moretext);
            } else {
                $(this).addClass("less");
                $(this).html(lesstext);
            }
            $(this).parent().prev().toggle();
            $(this).prev().toggle();
            return false;
        });
    });
</script>
@endsection