routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 

Auth::routes();

Route::group(['middleware' => ['admin','auth']], function () {
    Route::prefix('admin')->group(function () {
    // Route::namespace('admin')->group(function () {


        Route::get('dashboard', 'HomeController@index')->name('admin.dashboard');

        Route::resource('galleries','GalleriesController');
        Route::get('galleries-status/{id}/{opr}','GalleriesController@status')->name('admin.galleries.status');

        Route::resource('news','NewsController');
        Route::get('news-status/{id}/{opr}','NewsController@status')->name('admin.news.status');

        Route::resource('welcome','WelcomeController');
        Route::get('welcome-status/{id}/{opr}','WelcomeController@status')->name('admin.welcome.status');

        Route::resource('homeslider','HomeSliderController');
        Route::get('homeslider-status/{id}/{opr}','HomeSliderController@status')->name('admin.homeslider.status');
        Route::post('homeslider-set-position','HomeSliderController@set_sliders_position')->name('admin.homeslider.set.position');

        Route::resource('contactus','ContactusController');
        Route::post('set-contact','OptionsController@set_contact_us')->name('admin.set.contact');

        Route::resource('countries','CountriesController');
        Route::get('countries-status/{id}/{opr}','CountriesController@status')->name('admin.countries.status');

        Route::resource('homesizes','HomesizesController');
        Route::get('homesizes-status/{id}/{opr}','HomesizesController@status')->name('admin.homesizes.status');

        Route::resource('brokers','BrokersController');
        Route::get('brokers-status/{id}/{opr}','BrokersController@status')->name('admin.brokers.status');

        Route::resource('references','ReferencesController');
        Route::get('references-status/{id}/{opr}','ReferencesController@status')->name('admin.references.status');

        Route::resource('aboutus','AboutUsController');
        Route::get('aboutus-status/{id}/{opr}','AboutUsController@status')->name('admin.aboutus.status');

        Route::resource('aboutustabs','AboutUsTabsController');
        Route::get('aboutustabs-status/{id}/{opr}','AboutUsTabsController@status')->name('admin.aboutustabs.status');

    // });
  });
});


Route::get('/',function(){
    return redirect('main');
});

/* get data from below route */

Route::get('get-home-welcome','WelcomeController@get_home_welcome');
Route::get('get-contact-country','CountriesController@get_contact_country');
Route::get('get-contact-homesizes','HomesizesController@get_contact_homesizes');
Route::get('get-contact-brokers','BrokersController@get_contact_brokers');
Route::get('get-contact-references','ReferencesController@get_contact_references');
Route::get('get-option/{type}','OptionsController@get_option');
Route::post('apply-for-enquiry','ContactusController@create');

Route::get('get-home-sliders','HomeSliderController@get_homesliders');
Route::get('get-news','NewsController@get_news');
Route::get('get-single-news/{slug}','NewsController@get_single_news');

Route::get('get-galleries/{type}','GalleriesController@get_galleries');

/* dont touch the above path */

/* Below Is Vue Router Path */
Route::get('vue/{any?}/{id?}', function () {
    return view('front.home');
});


/* Below Is PHP Page Path */
Route::get('main', function () {
    return view('main');
})->name('main');

Route::get('slider', function () {
    return view('slider');
})->name('slider');

Route::get('gallery', function () {
    return view('gallery');
})->name('gallery');

Route::get('contact', function () {
    return view('contact');
})->name('contact');

Route::get('slide', function () {
    return view('slide');
})->name('slide'); 

Route::get('news', function () {
    return view('news');
})->name('news');

Route::get('smart&security', function () {
    return view('smart&security');
})->name('smart&security');

Route::get('amenities', function () {
    return view('amenities');
})->name('amenities');

Route::get('ace', function () {
    return view('ace');
})->name('ace');

Route::get('lifestyle', function () {
    return view('lifestyle');
})->name('lifestyle');

Route::get('location', function () {
    return view('location');
})->name('location');

Route::get('ssgf', function () {
    return view('ssgf');
})->name('ssgf');

Route::get('floor_plan', function () {
    return view('floor_plan');
})->name('floor_plan');

Route::get('views', function () {
    return view('views');
})->name('views');

Route::get('about', function () {
    return view('about');
})->name('about');

Route::get('single_news', function () {
    return view('single_news');
})->name('single_news');


Route::get('/dashboard',function(){
    return redirect('dashboard.index');
});


Route::prefix('dashboard')->group(function () {
    
    Route::get('index', function () {
        return view('dashboard/index');
    })->name('dashboard.index');

    Route::get('gallery', function () {
        return view('dashboard/gallery');
    })->name('dashboard.gallery');

    Route::get('news', function () {
        return view('dashboard/news');
    })->name('dashboard.news');

});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="universal admin is super flexible, powerful, clean & modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, universal admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="pixelstrap">

    <link rel="icon" href="{{ asset('back/images/favicon.png') }}" type="image/x-icon" />
    <link rel="shortcut icon" href="{{ asset('back/images/favicon.png') }}" type="image/x-icon" />
    <title>@yield('title')</title>

    <!--Google font-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700" rel="stylesheet">

    <!-- Font Awesome -->
    <link rel="stylesheet" type="text/css" href="{{ asset('back/css/fontawesome.css') }}">

    <!-- ico-font -->
    <link rel="stylesheet" type="text/css" href="{{ asset('back/css/icofont.css') }}">

    <!-- Themify icon -->
    <link rel="stylesheet" type="text/css" href="{{ asset('back/css/themify.css') }}">

    <!-- Flag icon -->
    <link rel="stylesheet" type="text/css" href="{{ asset('back/css/flag-icon.css') }}">

    <!--JSGrid css-->
    <link rel="stylesheet" type="text/css" href="{{ asset('back/css/datatables.css') }}" />

    <!-- Bootstrap css -->
    <link rel="stylesheet" type="text/css" href="{{ asset('back/css/bootstrap.css') }}">

    <!-- App css -->
    <link rel="stylesheet" type="text/css" href="{{ asset('back/css/style.css') }}">

    <!-- Responsive css -->
    <link rel="stylesheet" type="text/css" href="{{ asset('back/css/responsive.css') }}">

    <link rel="stylesheet" type="text/css" href="{{ asset('back/css/toastr.css') }}">

    @yield('style')
</head>

<body>

<!-- Loader starts -->
<!-- <div class="loader-wrapper">
    <div class="loader bg-white">
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
        <h4>Have a great day at work today <span>&#x263A;</span></h4>
    </div>
</div> -->
<!-- Loader ends -->

<!--page-wrapper Start-->
<div class="page-wrapper">

    <!--Page Header Start-->
    @include('layouts.header')
    <!--Page Header Ends-->

    <!--Page Body Start-->
    <div class="page-body-wrapper">
        <!--Page Sidebar Start-->
        @include('layouts.sidebar')
        <!--Page Sidebar Ends-->

        <div class="page-body">
            @yield('content')
        </div>
    </div>
    <!--Page Body Ends-->

</div>
<!--page-wrapper Ends-->

<!-- latest jquery-->
<script src="{{ asset('back/js/jquery-3.2.1.min.js') }}"></script>

<!-- Bootstrap js-->
<script src="{{ asset('back/js/popper.min.js') }}"></script>
<script src="{{ asset('back/js/bootstrap.js') }}"></script>

<!-- Sidebar jquery-->
<script src="{{ asset('back/js/sidebar-menu.js') }}"></script>

<!--Datatable js-->
<script src="{{ asset('back/js/jquery.dataTables.min.js') }}"></script>

<script src="{{ asset('back/js/toastr.min.js') }}"></script>

<script>
  @if(Session::has('message'))
    var type = "{{ Session::get('alert-type', 'info') }}";
    switch(type){
        case 'info':
            toastr.info("{{ Session::get('message') }}");
            break;
        
        case 'warning':
            toastr.warning("{{ Session::get('message') }}");
            break;

        case 'success':
            toastr.success("{{ Session::get('message') }}");
            break;

        case 'error':
            toastr.error("{{ Session::get('message') }}");
            break;
    }
  @endif
</script>

@yield('script')

</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">


    <!-- full page -->
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.9.7/jquery.fullpage.min.css" />
    
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    </div>
</body>
</html>

resources/views/layouts/header.blade.php
<div class="page-main-header">
    <div class="main-header-left">
        <div class="logo-wrapper">
            <a href="">
                
            </a>
        </div>
    </div>
    <div class="main-header-right row">
        <div class="mobile-sidebar">
            <div class="media-body text-right switch-sm">
                <label class="switch">
                    <input type="checkbox" id="sidebar-toggle" checked>
                    <span class="switch-state"></span>
                </label>
            </div>
        </div>
        <div class="nav-right col">
            <ul class="nav-menus">
                <li class="onhover-dropdown">
                    <div class="media  align-items-center">
                        <div class="media-body">
                            <h6 class="m-0 txt-dark f-16">
                                {{ Auth::user()->name }}
                                <i class="fa fa-angle-down pull-right ml-2"></i>
                            </h6>
                        </div>
                    </div>
                    <ul class="profile-dropdown onhover-show-div p-20">
                        <li>
                            <a href="#">
                                <i class="icon-user"></i>
                                Edit Profile
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                <i class="icon-power-off"></i>
                                {{ __('Logout') }}
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            </form>
                        </li>
                    </ul>
                </li>
            </ul>
            <div class="d-lg-none mobile-toggle">
                <i class="icon-more"></i>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/sidebar.blade.php
<div class="page-sidebar custom-scrollbar">
    <div class="sidebar-user text-center">
        <div>
            <img class="img-50 rounded-circle" src="{{ asset('back/images/user/1.jpg') }}" alt="#">
        </div>
        <h6 class="mt-3 f-12">{{ Auth::user()->name }}</h6>
    </div>
    <ul class="sidebar-menu">
        <li>
            <div class="sidebar-title">General</div>
            <a href="{{ route('admin.dashboard') }}" class="sidebar-header">
                <i class="icon-desktop"></i><span>Dashboard</span>
                <i class="fa fa-angle-right pull-right"></i>
            </a>
            <ul class="sidebar-submenu">
                <li><a href="{{ route('admin.dashboard') }}"><i class="fa fa-angle-right"></i>Default</a></li>
                <li><a href="{{ route('admin.dashboard') }}"><i class="fa fa-angle-right"></i>E-commerce</a></li>
                <li><a href="{{ route('admin.dashboard') }}"><i class="fa fa-angle-right"></i>Business<span class="badge badge-secondary ml-3">Tour</span></a></li>
                <li><a href="{{ route('admin.dashboard') }}"><i class="fa fa-angle-right"></i>CRM</a></li>
            </ul>
        </li>
        <li>
            <a href="{{ route('galleries.index') }}" class="sidebar-header">
                <i class="icon-desktop"></i><span>Galleries</span>
            </a>
        </li>
        <li>
            <a href="{{ route('news.index') }}" class="sidebar-header">
                <i class="icon-desktop"></i><span>News</span>
            </a>
        </li>
        <li>
            <a href="{{ route('welcome.index') }}" class="sidebar-header">
                <i class="icon-desktop"></i><span>Welcome</span>
            </a>
        </li>
        <li>
            <a href="{{ route('homeslider.index') }}" class="sidebar-header">
                <i class="icon-desktop"></i><span>Home Slider</span>
            </a>
        </li>
        <li>
            <a href="" class="sidebar-header">
                <i class="icon-desktop"></i><span>Contact</span>
                <i class="fa fa-angle-right pull-right"></i>
            </a>
            <ul class="sidebar-submenu">
                <li><a href="{{ route('contactus.index') }}"><i class="fa fa-angle-right"></i>Enquires</a></li>
                <li><a href="{{ route('countries.index') }}"><i class="fa fa-angle-right"></i>Countries</a></li>
                <li><a href="{{ route('homesizes.index') }}"><i class="fa fa-angle-right"></i>Homesizes</a></li>
                <li><a href="{{ route('brokers.index') }}"><i class="fa fa-angle-right"></i>Brokers</a></li>
                <li><a href="{{ route('references.index') }}"><i class="fa fa-angle-right"></i>References</a></li>
            </ul>
        </li>

        <li>
            <a href="" class="sidebar-header">
                <i class="icon-desktop"></i><span>About Us</span>
                <i class="fa fa-angle-right pull-right"></i>
            </a>
            <ul class="sidebar-submenu">
                <li><a href="{{ route('aboutus.index') }}"><i class="fa fa-angle-right"></i>About Sections</a></li>
                <li><a href="{{ route('aboutustabs.index') }}"><i class="fa fa-angle-right"></i>About Tabs</a></li>
            </ul>
        </li>
    </ul>
</div>